//Given two strings s and t which consist of only lowercase letters.
//
//String t is generated by random shuffling string s and then add one more letter at a random position.
//
//Find the letter that was added in t.
//
//Example:
//
//    Input:
//    s = "abcd"
//    t = "abcde"
//
//    Output:
//        e
//
//    Explanation:
//    'e' is the letter that was added.

#include <iostream>

using namespace std;

class Solution_389 {
public:
    // Exp: https://discuss.leetcode.com/topic/55940/concise-c-solution-using-xor
    // Time:	O(n)
    // Space:	O(1)
    char findTheDifference(string s, string t) {
        char result = 0;
        for (char &c : s)
            result ^= c;
        for (char &c : t)
            result ^= c;
        return result;
    }
};